### ISSUE TITLE
`getFragment` vs. `readFragment`

### ISSUE THREAD

**Issue by TimonVS** [abhiaiyer91/apollo-fragment#10]
Hi Abhi, I recently came across this library and I think it's a great it's a great idea and I'd like to start using it. I was wondering what is the reason of adding a `getFragment` resolver instead of using Apollo's [`readFragment`](https://www.apollographql.com/docs/react/advanced/caching.html#readfragment)? You probably had a good reason to do it this way, but I was just curious :)

**Comment by abhiaiyer91** [comment]
Oh the name was just arbitrary! The reason we setup a resolver is so when we get a query to it we can add a cache redirect and then pick out the Fragment from cache. A lot of this should be invisible to the users of this library’
