### ISSUE TITLE
Cannot read property `replace` of undefined

### ISSUE THREAD

**Issue by masiamj** [abhiaiyer91/apollo-fragment#9]
Hi all,

This package looks great, and exactly like what I'm looking for; however, I'm having a really tough time getting the implementation right.

Here's a couple key pieces of my implementation:

**Apollo Cache**
<img width="489" alt="screen shot 2018-08-09 at 4 36 58 pm" src="https://user-images.githubusercontent.com/7084914/43924550-f1711334-9bf2-11e8-90b0-a142efe68fab.png">

**ApolloFragment Usage**
<img width="552" alt="screen shot 2018-08-09 at 4 37 58 pm" src="https://user-images.githubusercontent.com/7084914/43924576-011b494e-9bf3-11e8-8183-d9fc3054a7e7.png">

**Fragment**
<img width="464" alt="screen shot 2018-08-09 at 4 38 51 pm" src="https://user-images.githubusercontent.com/7084914/43924675-38a9a3a6-9bf3-11e8-89ff-f6c163a27d74.png">

**Error**
<img width="1086" alt="screen shot 2018-08-09 at 4 39 00 pm" src="https://user-images.githubusercontent.com/7084914/43924607-10a4888a-9bf3-11e8-90ff-46a1d3c0b0e2.png">

Do you see anything obvious about why I'd be receiving this error? My bet is it's something trivial, just having a tough time debugging for now.

Thanks for your help!

**Comment by dehypnosis** [comment]
same here..

**Comment by abhiaiyer91** [comment]
Hi there!

Internally, ApolloFragment wraps the fragment string passed in with `gql`. So in order for the above to work, drop the `gql` and just pass it in as a string.

We could do a check in the library to see if fragment is already a `DocumentNode` and omit wrapping `gql` internally! 

Would love to see that PR!

**Comment by abhiaiyer91** [comment]
Also the `typename` prop is extracted from the fragment passed in.
